### ISSUE TITLE
Group project initial review

### ISSUE THREAD

**Issue by audip** [cpoutfitters/cpoutfitters#1]
Our group project is ready with the required and optional stories. Please review, /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Great to see your GitHub repository setup and user stories defined! The user stories are a key piece of the group project. They help you prioritize the most important parts of the app to build. It's particularly important that you've split the user stories into "Required" and "Optional" stories so your team can focus on the most important aspects of the app first and then add in the optionals as time permits toward the end of the project.

I do love your idea and I'm looking forward to see it become a real app :wink: 

Next week we'll move on to the next step of the group project by doing something called wireframing, which is creating a blueprint for the app.
