### ISSUE TITLE
Error in fetching articles

### ISSUE THREAD

**Issue by audip** [cpoutfitters/cpoutfitters#11]
I am not able to resolve this thing, don't know why this keeps failing again and again. It would be great if you could take a look, @lochiego https://github.com/cpoutfitters/cpoutfitters/tree/feature/app-model-article

**Comment by lochiego** [comment]
Can you be more specific?

**Comment by audip** [comment]
So I made corrections to article and corrected fetch articles function. But when I run tests, no objects return. Can you figure out what's wrong? 

Apart from that, fetch, save and delete articles should work with our front end

Aditya Purandare

**Comment by audip** [comment]
When I try saving an article on mLab, it creates a new article document but doesn't have any data. When I try fetching data for sample Article that @lochiego created, my function works well. So, in my opinion my Parse client is working, just it's complicated because it's not able to save and fetch articles. Should we ask CodePath for help?

**Comment by audip** [comment]
When I use this syntax, 

```
    article["owner"] = PFUser.currentUser()!

    article["type"] = "shirt"

    article["short"] = true

    article["primary_color"] = "blue"
```

The output is: 
<img width="761" alt="screenshot 2016-03-22 20 52 33" src="https://cloud.githubusercontent.com/assets/4290846/13973357/07cd8a1c-f070-11e5-9b19-e9652783f12c.png">

My suspicion is towards the default constructor `init()` in Article class and our object creation 
`let Article = Article()` calling the default constructor instead of the `init(object: PFObject)`

Do you have any workaround in mind @cthompson527 @lochiego ?
