### ISSUE TITLE
[Week 3] CPOutfitters progress update - review our app

### ISSUE THREAD

**Issue by audip** [cpoutfitters/cpoutfitters#19]
Our app is complete after the third week of group assignment with team: @cthompson527 @lochiego . Please review. /cc @codepathreview

Here's the GIF:
![cpoutfitters-sprint-week-3](https://cloud.githubusercontent.com/assets/4290846/14375245/11fb0390-fd25-11e5-8782-a7800e09aecb.gif)

**Comment by minhchau273** [comment]
:+1: Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app.
Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
