### ISSUE TITLE
Wireframes ready for review

### ISSUE THREAD

**Issue by lochiego** [cpoutfitters/cpoutfitters#2]
/cc @codepathreview

![wireframes](https://cloud.githubusercontent.com/assets/1099038/13416147/27a2969e-df26-11e5-950e-9b9919fb0c39.png)

**Comment by minhchau273** [comment]
:+1: Nice job on the wireframes! Wireframing is a common practice when building apps as it lets you create a blueprint for the app before writing any code. Having a really good blueprint that you can refer to throughout the rest of the project is a really valuable resource and will make it much easier to split up work across your team.

The wireframes make me a little confused :confused: I cannot imagine the flow how your app suggests outfits to help me dress better. Can you explain more detailed?

With the wireframes in hand, you should have a good idea of what your app will look like when you finish the project. Next week we'll jump into the data schema.
