### ISSUE TITLE
Schema ready for review

### ISSUE THREAD

**Issue by lochiego** [cpoutfitters/cpoutfitters#3]
/cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Nice work on getting the data schema defined! Good job with the very detailed schema :100: 

I have some questions:
- What is `shared_with`? There're 4 models having this property. :question: 
- I think the relationship between `User` and `Feedback` should be `1-n`.
- What is the difference between `Outfit` an`Scheduled_outfit` and the relationship between them? Why does the `Scheduled_outfit` have a property `feedback: String`? Is this feedback a instance of `Feedback` model?
- Your data schema looks like missing some weak entities to describe the many-to-may relationships. :confused: 

Next week we jump into the first implementation sprint. You'll have 3 sprints (one week each) to complete all the required stories for your app and 2 sprints (one week each) to work on optionals and add polish. Let us know if we can help in any way!
