### ISSUE TITLE
Create Data models

### ISSUE THREAD

**Issue by lochiego** [cpoutfitters/cpoutfitters#4]
Define our data models which wrap PFObject and define the relationship between them. Will be handled by @audip

**Comment by audip** [comment]
@lochiego Do we need to have relationships in Article class with Wardrobe?

**Comment by lochiego** [comment]
@audip Articles are part of a wardrobe, in that a wardrobe is a collection of articles. I don't think we need to go the other direction.

**Comment by audip** [comment]
Have a look at Article class:
https://github.com/cpoutfitters/cpoutfitters/blob/feature/app-model/CPOutfitters/Article.swift

From the schema, how do we link wardrobe_id in article entity?

<img width="329" alt="screenshot 2016-03-11 23 17 34" src="https://cloud.githubusercontent.com/assets/4290846/13721050/76467b5a-e7df-11e5-80f8-95bdb5cf3cf4.png">

**Comment by lochiego** [comment]
Parse should handle that. They allegedly handle all the relationships between your items, from what I remember.
